# Generated by Django 5.0.2 on 2025-06-28 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_emojireaction_emoji_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='emojireaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='trendingtag',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='trendingtag',
            name='post_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post'], name='posts_comme_post_id_06cfd5_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user'], name='posts_comme_user_id_5151d7_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent'], name='posts_comme_parent__6e2946_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='posts_comme_created_f825cb_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'parent'], name='posts_comme_post_id_ab98e8_idx'),
        ),
        migrations.AddIndex(
            model_name='emojireaction',
            index=models.Index(fields=['post'], name='posts_emoji_post_id_3881ec_idx'),
        ),
        migrations.AddIndex(
            model_name='emojireaction',
            index=models.Index(fields=['user'], name='posts_emoji_user_id_c9fff5_idx'),
        ),
        migrations.AddIndex(
            model_name='emojireaction',
            index=models.Index(fields=['emoji'], name='posts_emoji_emoji_92c100_idx'),
        ),
        migrations.AddIndex(
            model_name='emojireaction',
            index=models.Index(fields=['post', 'user'], name='posts_emoji_post_id_8e2fb1_idx'),
        ),
        migrations.AddIndex(
            model_name='emojireaction',
            index=models.Index(fields=['post', 'emoji'], name='posts_emoji_post_id_2bd973_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author'], name='posts_post_author__19d68b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at'], name='posts_post_created_dadbfe_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'created_at'], name='posts_post_author__d94160_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='posts_tag_name_f0f1cb_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['slug'], name='posts_tag_slug_ca6fc4_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['created_at'], name='posts_tag_created_195580_idx'),
        ),
        migrations.AddIndex(
            model_name='trendingtag',
            index=models.Index(fields=['tag'], name='posts_trend_tag_id_c94bab_idx'),
        ),
        migrations.AddIndex(
            model_name='trendingtag',
            index=models.Index(fields=['post_count'], name='posts_trend_post_co_da95f6_idx'),
        ),
        migrations.AddIndex(
            model_name='trendingtag',
            index=models.Index(fields=['last_updated'], name='posts_trend_last_up_c62488_idx'),
        ),
    ]
